version: '3'
services:

  mysql:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: vollmed
      MYSQL_DATABASE: vollmed
      MYSQL_USER: vollmed
      MYSQL_PASSWORD: vollmed